### ISSUE TITLE
Lots of text missing in PDFs

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Sampler#10]

**Comment by hartytp** [comment]
Also, SHDN for IC1.

Some Altium bug?

**Comment by hartytp** [comment]
I take it back. At least in my PDF viewer, there is lots of text missing from the PDF, making the review hard

**Comment by gkasprow** [comment]
There was AD update recently, I will regenerate it.

**Comment by gkasprow** [comment]
OK, I regenerated with AD18 and it is fine.

**Comment by hartytp** [comment]
@gkasprow Sorry for the delay, where are the new schematics?

**Comment by gkasprow** [comment]
[here](https://github.com/sinara-hw/Sampler/releases/tag/Sampler%2Fv2.2rc1)
