### ISSUE TITLE
Change BNC connectors

### ISSUE THREAD

**Issue by dtcallcock** [sinara-hw/Sampler#13]
Sampler is the only place in Sinara where one is forced to use BNCs and an 8HP panel.

Standardising all boards to 4HP may be advantageous for [a future backplane](https://github.com/sinara-hw/meta/issues/30#issuecomment-444467090).

MMCX would be an obvious choice as we are already using it for the Sayma v2 AFE analog inputs and Stabilizer aux digital inputs. However, they are a bit on the small side and easy to disengage compared SMB/MCX so one might worry about mechanical robustness. SMC/Micro BNC/LEMO all seem somewhat less ubiquitous and more expensive. My slight preference would be for MCX, but it would be good to hear from people with more experience.  I'm not totally sure how you would isolate this kind of connector from the front panel though (just a clearance hole?).

Even if we all agreed this is a brilliant idea, it probably doesn't warrant a board revision right away.  I did want to leave an issue open in this repository for future reference though.

**Comment by dhslichter** [comment]
Just need to think a little about crosstalk (granted, BNC is not great for this either).  But I agree that MCX or SMB or other smaller connectors would be nice.

**Comment by dtcallcock** [comment]
@hartytp makes the point that:

> Personally, I also like BNCs. Much quicker to swap in and out. Much easier to make ones own cables to length quickly and cheaply.

It seems that MCX is even easier to swap in and out than BNC and connectors are available that, at first glance, don't look any harder to assemble than a BNC connector (eg. [this](https://www.digikey.com/product-detail/en/molex-llc/0733660020/WM5388-ND/2755904) RG-316 connector).

However I do buy the argument that most labs have a lot of BNC stuff around and a proliferation of random connectors across Sinara should be avoided (hence my opinion that we should just pick one general BNC replacement).  The board could also optionally ship with 8 BNC pigtails.

> Just need to think a little about crosstalk (granted, BNC is not great for this either).

A random search suggests that MCX might have >70dB RF leakage (compared to >100dB for an SMA and >55dB for BNC).  MMCX seems similar to MCX and SMB seems similar to BNC.  Exact numbers depend on mfg/cable obviously.

**Comment by dhslichter** [comment]
SMB leakage is lousy, so I generally don't like them.  If MCX is better then rock on.

**Comment by dtcallcock** [comment]
Btw, we have one of these Seeed mini-scopes with MCX connectors on it and they seem pretty nice to me.  

It shipped with the kind of BNC pigtails that @gkasprow mentioned.  I also found some SMA adaptors that enable use of standard SMA cables, but at high density (as one doesn't have to leave room for the torque wrench).

![img_3199](https://user-images.githubusercontent.com/20587606/50239643-0240a900-0380-11e9-8a98-be860355f56c.jpg)

**Comment by gkasprow** [comment]
DSO203? I have such model for 4 years or so and can confirm that these probe connectors work reliably.

**Comment by jordens** [comment]
Could be my "DSO Quad" and would be 6 or 7 years old now.

**Comment by gkasprow** [comment]
The assembly house asked us to make some cosmetic changes that would improve the production yield.
I will also add mounting holes for CPCIS adapter. Do we plan to change the BNC connectors and switch to 4HP?

**Comment by gkasprow** [comment]
MCX version would look like this
![obraz](https://user-images.githubusercontent.com/4325054/52972578-9c8e8e80-33bb-11e9-9525-167d21438e33.png)

**Comment by hartytp** [comment]
I’m happy with either BNC or MCX

**Comment by jordens** [comment]
Go for mcx.

**Comment by gkasprow** [comment]
Do you want MCX-BNC adapters to be delivered with Sampler?
Would such cable be fine?
![obraz](https://user-images.githubusercontent.com/4325054/52979228-fa7ba000-33d4-11e9-8560-89ed7053d03d.png)

They cost roughly 2EUR/pc

**Comment by jordens** [comment]
Ah. One thing to check: those small mcx to sma bullet adapters. Do they fit or is the pitch to small for sma?
Yes. I'd include 8 of those pigtails.

**Comment by gkasprow** [comment]
I tried with the biggest SMA-MCX adapters I could find and it will work. Of course, SMA needs to be attached prior to plugging. I do not recommend using these adapters with thick and long SMA cables because they will add tension to the MCX connectors and the PCB. Cable adapters seem to be a better choice.

![obraz](https://user-images.githubusercontent.com/4325054/53051862-848f3b80-349d-11e9-9227-af8f6aedca52.png)

**Comment by gkasprow** [comment]
There is no collision with the handle
![obraz](https://user-images.githubusercontent.com/4325054/53052055-fb2c3900-349d-11e9-9775-83ec130c58da.png)

**Comment by dtcallcock** [comment]
+1 for MCX and pigtails

**Comment by hartytp** [comment]
@gkasprow @jordens and others, do we want to do anything here for the next revision, or leave this to further down the line? I'm okay with MCX so long as we ship with MCX to BNC pigtails.

**Comment by gkasprow** [comment]
The Sampler board can be ordered with MCX adapter board, so I'm leaving it as it is now with BNCs.

**Comment by dtcallcock** [comment]
Added note about this to wiki.

**Comment by gkasprow** [comment]
Btw, one can already order such Samplers. TS did a production run AFAIK.
