### ISSUE TITLE
Wiki: update EEM connector pinout

### ISSUE THREAD

**Issue by airwoodix** [sinara-hw/Sampler#18]
To match Sampler v2.x:
- add `ADC-SDOA` output to EEM1 pair 1 (and shift the other `SDOx` accordingly);
- shift `ADC-SDOA` output on EEM0 to pair 1;
- add `ADC-SDR` input to EEM0 pair 2.

Although pretty obvious, a direction indication would be great I think.

**Comment by jordens** [comment]
Thanks!
Greg added you. You should be able to edit the wiki yourself.

**Comment by airwoodix** [comment]
Great, thanks a lot! Changes done.
